### ISSUE TITLE
PhoneNumber test suite - two tests fail to recognise assertion raised

### ISSUE THREAD

**Issue by AronNaylor** [exercism/python#2207]
**Issue**

Running the supplied phone_number_test.py two tests are failing to capture that an assertion with a message is raised. Other tests that utilise the same assertRaisesWithMessage do pass, however.

**Code**
```
import string

class PhoneNumber:
    def __init__(self, number):
        self.number = ''.join([el for el in number if el in string.digits])

        if len(self.number) <= 9 or len(self.number) > 11:
            raise ValueError('Number length is incorrect')
        elif len(self.number) == 11:
            if self.number.startswith('1'):
                self.number = self.number[1::]
                if self.number.startswith('0') or self.number.startswith('1'):
                    print('+++ This fires +++')
                    raise ValueError('Incorrect area code')
            else:
                raise ValueError('Number does not start with 1')
        elif self.number[0] == '0' or self.number[0] == '1':
            raise ValueError('Incorrect area code') 
        elif self.number[3] == '0' or self.number[3] == '1':
            raise ValueError('Incorrect exchange code')

    def area_code(self):
        return self.number[:3]

    def pretty(self):
        return '('+ self.number[:3] +') ' + self.number[3:6] + '-' + self.number[6::]
```
**Tests which fail**
```
def test_invalid_if_area_code_starts_with_0_on_valid_11_digit_number(self):
        with self.assertRaisesWithMessage(ValueError):
            PhoneNumber("1 (023) 456-7890")

def test_invalid_if_area_code_starts_with_1_on_valid_11_digit_number(self):
        with self.assertRaisesWithMessage(ValueError):
            PhoneNumber("1 (123) 456-7890")
```
**Pytest output**
```
=========================================================================== FAILURES =========================================================================== 
_____________________________________ PhoneNumberTest.test_invalid_if_exchange_code_starts_with_0_on_valid_11_digit_number _____________________________________ 

self = <phone_number_test.PhoneNumberTest testMethod=test_invalid_if_exchange_code_starts_with_0_on_valid_11_digit_number>

    def test_invalid_if_exchange_code_starts_with_0_on_valid_11_digit_number(self):
        with self.assertRaisesWithMessage(ValueError):
>           PhoneNumber("1 (223) 056-7890")
E           AssertionError: ValueError not raised

phone_number_test.py:75: AssertionError
_____________________________________ PhoneNumberTest.test_invalid_if_exchange_code_starts_with_1_on_valid_11_digit_number _____________________________________ 

self = <phone_number_test.PhoneNumberTest testMethod=test_invalid_if_exchange_code_starts_with_1_on_valid_11_digit_number>

    def test_invalid_if_exchange_code_starts_with_1_on_valid_11_digit_number(self):
        with self.assertRaisesWithMessage(ValueError):
>           PhoneNumber("1 (223) 156-7890")
E           AssertionError: ValueError not raised

phone_number_test.py:79: AssertionError
=================================================================== short test summary info ==================================================================== 
FAILED phone_number_test.py::PhoneNumberTest::test_invalid_if_exchange_code_starts_with_0_on_valid_11_digit_number - AssertionError: ValueError not raised       
FAILED phone_number_test.py::PhoneNumberTest::test_invalid_if_exchange_code_starts_with_1_on_valid_11_digit_number - AssertionError: ValueError not raised       
================================================================= 2 failed, 19 passed in 0.78s =================================================================
```

**Console output when replicating tests manually**
```
+++ This fires +++
Traceback (most recent call last):
  File "Exercism/python/phone-number/phone_number.py", line 28, in <module>
    PhoneNumber("1 (123) 456-7890")
  File "Exercism/python/phone-number/phone_number.py", line 14, in __init__
    raise ValueError('Incorrect area code')
ValueError: Incorrect area code
```

**Comment by cmccandless** [comment]
Hi @AronNaylor 

Since you've already closed this issue, I hope you found the solution you were looking for.
